project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Yilin Zhang"
  site-url: https://yilinzhang.github.io
  favicon: images/site.png
  repo-url: https://github.com/AliciaFlorrie/yilinzhang.github.io
  repo-actions: [edit, issue]
  
  # page-footer:
  #   left: |
  #     [lianxh.cn](https://www.lianxh.cn)<br>
  #   right: |
  #     Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CV_Yilin_Zhang.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细