---
title: "中文简历"
editor: 
  markdown: 
    wrap: 72
---

## 个人简介

张艺琳，女，本科毕业于东北大学（中国），专业前20%保研本校，目前硕士二年级在读。硕士研究期间主要方向为大语言模型的应用，包括大模型的微调，RAG，多模态等。在2024年-2025年期间我参加了College of William & Mary的暑期科研实习，指导教师为Dr. Yanfu Zhang (https://yaz91.github.io/)。在实习期间我利用GNN和大模型技术完成阿尔兹海默症分析，并投稿SCI论文一篇“Self-Guided Graph Neural Network with Integrated Knowledge for Alzheimer's Disease”；使用强化学习-多臂老虎机算法协助医院为患者治疗，投递论文一篇“Deep Learning on Meta-Analytic Data for Therapeutic Decision-Making in Central Nervous System Aspergillosis”。2025年年初Deepseek R1兴起至今，协助导师陈东岳完成实验室项目“智慧助教”，目前在校园内上线。

- 邮箱：zhangyilin_1225@foxmail.com (优先); yilinzhang@stumail.neu.edu.cn; aliciaflorrie@gmail.com
- 电话：+86 15524011185
- 地址：辽宁省沈阳市和平区文化路3巷11号东北大学 （110819）
- 博客：<https://blog.csdn.net/weixin_51709535?type=blog>
- Github: <https://github.com/AliciaFlorrie>
- 个人主页：<https://yilinzhang.github.io>

## 教育和工作背景

- 2001.09-2007.07 东北大学 信息科学与工程学院 模式识别与智能系统 硕士(在读)
- 2019.9-2023.7 东北大学 信息科学与工程学院 自动化 本科(工学学士)


## 研究兴趣

- 自然语言处理
- 大语言模型（强化学习，大模型微调，RAG系统）
- 多模态


## 自我评价

- 具备主观能动性和一定的自学能力，能够主动发现问题并提出解决方案
- 沟通协调能力强，能够清晰表达观点参与团队协作
- 具备好奇心，希望发现问题并研究问题的本质



## 论文成果
-   **Yilin Zhang**, Zhepeng Wang, Guodong Liu, Yanfu Zhang. Self-Guided Graph Neural Network with Integrated Knowledge for Alzheimer’s Disease. **Biomedical Signal Processing and Control**, 2024, in review. 
-   Weina Lu, **Yilin Zhang**, Ran Ji. Deep Learning on Meta-Analytic Data for Therapeutic Decision-Making in Central Nervous System Aspergillosis. **BMC Infectious Diseases**, 2025, in review.
-   **Yilin Zhang**, PromptRAG: Stable Retrieval-augmented generation via reinforcement learning, in progress

